packages:
  - internal/*
  - packages/*

catalog:
  '@ant-design/colors': ^8.0.1
  '@ant-design/icons-vue': ^7.0.1
  '@eslint/js': ^9.39.2
  '@iconify/json': ^2.2.433
  '@iconify/vue': ^4.3.0
  '@jiaminghi/color': ^1.1.3
  '@logicflow/core': ^1.2.28
  '@logicflow/extension': ^1.2.28
  '@purge-icons/generated': ^0.10.0
  '@rollup/plugin-terser': ^0.4.4
  '@rushstack/eslint-patch': ^1.15.0
  '@stylistic/stylelint-plugin': ^3.1.3
  '@types/crypto-js': ^4.2.2
  '@types/eslint': ^9.6.1
  '@types/fs-extra': ^11.0.4
  '@types/inquirer': ^9.0.9
  '@types/intro.js': ^5.1.5
  '@types/jsdom': ^21.1.7
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.19.7
  '@types/nprogress': ^0.2.3
  '@types/qrcode': ^1.5.6
  '@types/qs': ^6.14.0
  '@types/sm-crypto': ^0.3.4
  '@types/sortablejs': ^1.15.9
  '@typescript-eslint/eslint-plugin': ^8.54.0
  '@typescript-eslint/parser': ^8.54.0
  '@vitejs/plugin-legacy': ^6.1.1
  '@vitejs/plugin-vue': ^5.2.4
  '@vitejs/plugin-vue-jsx': ^4.2.0
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/shared': ^3.5.27
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.9.0
  '@vueuse/shared': ^13.9.0
  '@zxcvbn-ts/core': ^3.0.4
  animate.css: ^4.1.1
  ant-design-vue: ^4.2.6
  ant-design-x-vue: ^1.6.0
  autoprefixer: ^10.4.23
  axios: ^1.13.4
  bootstrap: ^5.3.8
  codemirror: 5.65.16
  cropperjs: ^1.6.2
  cross-env: ^7.0.3
  crypto-js: ^4.2.0
  dayjs: ^1.11.19
  dotenv: ^16.6.1
  echarts: ^6.0.0
  echarts-gl: ^2.0.9
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-config-turbo: ^2.8.0
  eslint-plugin-command: ^0.2.7
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-jsdoc: ^50.8.0
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^56.0.1
  eslint-plugin-unused-imports: ^4.3.0
  eslint-plugin-vue: ^10.7.0
  esno: ^4.8.0
  fs-extra: ^11.3.3
  globals: ^15.15.0
  html2canvas: ^1.4.1
  inquirer: ^12.11.1
  jsdom: ^26.1.0
  jsonc-eslint-parser: ^2.4.2
  less: ^4.5.1
  lodash-es: ^4.17.23
  markdown-it: ^14.1.0
  naive-ui: ^2.43.2
  npm-run-all: ^4.1.5
  nprogress: ^0.2.0
  path-to-regexp: ^8.3.0
  picocolors: ^1.1.1
  pinia: ^3.0.4
  pkg-types: ^1.3.1
  postcss: ^8.5.6
  postcss-html: ^1.8.1
  postcss-scss: ^4.0.9
  prettier: ^3.8.1
  prettier-plugin-packagejson: ^2.5.22
  qrcode: ^1.5.4
  qs: ^6.14.1
  resize-observer-polyfill: ^1.5.1
  rimraf: ^6.1.0
  rollup: ^4.53.2
  rollup-plugin-visualizer: ^5.14.0
  sm-crypto: ^0.3.14
  sortablejs: ^1.15.6
  stylelint: ^16.26.1
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^37.0.0
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.14.0
  terser: ^5.46.0
  turbo: ^2.8.0
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.6.0
  uuid: ^11.1.0
  vite: ^7.2.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^3.9.1
  vite-plugin-html: ^3.2.2
  vite-plugin-imagemin: ^0.6.1
  vite-plugin-mkcert: ^1.17.9
  vite-plugin-mock: ^3.0.2
  vite-plugin-style-inject: ^0.0.1
  vite-plugin-svg-icons: ^2.0.1
  vite-plugin-vue-setup-extend: ^0.4.0
  vue: ^3.5.24
  vue-data-ui: ^3.13.7
  vue-eslint-parser: ^10.2.0
  vue-i18n: ^11.2.8
  vue-json-pretty: ^2.6.0
  vue-router: ^4.6.4
  vue-tsc: ^2.2.12
  vue-types: ^6.0.0
  vuedraggable: ^4.1.0
